test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-
 arrow() {
   echo '----->' "$@"
 }
@@ -9,32 +8,83 @@ indent() {
   sed -u 's/^/       /'
 }
 
+
+
+# fail fast
+set -e
+
+# config
+APACHE_VERSION="2.2.22"
+APACHE_PATH="apache"
+PHP_VERSION="5.3.10"
+PHP_PATH="php"
+
+BIN_DIR=$(dirname $0)
 BUILD_DIR=$1
+CACHE_DIR=$2
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
-# Get microsoft ODBC diver version
-for f in ${BUILD_DIR}/.apt/opt/microsoft/*; do
-  echo $f
-	MS_ODBC_VERSION=$(echo "$(basename $f)" | grep -o -E '[0-9]+')
-	break;
+# include .files when moving things around
+shopt -s dotglob
+
+cd $BUILD_DIR
+
+# move app things to www
+mkdir -p $CACHE_DIR/www
+mv * $CACHE_DIR/www
+mv $CACHE_DIR/www .
+
+# keep Procfile
+if [ -f www/Procfile ]; then
+  mv www/Procfile .
+fi
+
+APACHE_URL="https://s3.amazonaws.com/php-lp/apache-$APACHE_VERSION.tar.gz"
+echo "-----> Bundling Apache version $APACHE_VERSION"
+curl --silent --max-time 60 --location "$APACHE_URL" | tar xz
+
+PHP_URL="https://s3.amazonaws.com/php-lp/php-$PHP_VERSION.tar.gz"
+echo "-----> Bundling PHP version $PHP_VERSION"
+curl --silent --max-time 60 --location "$PHP_URL" | tar xz
+
+# update config files
+cp $LP_DIR/conf/httpd.conf $APACHE_PATH/conf
+cp $LP_DIR/conf/php.ini php
+
+# make php available on bin
+mkdir -p bin
+ln -s /app/php/bin/php bin/php
+
+# check if we have Composer dependencies and vendors are not bundled
+if [ -f www/composer.json ] && [ ! -d www/vendor ]; then
+  GIT_DIR_ORIG=$GIT_DIR
+  unset GIT_DIR
+  echo "-----> Installing Composer dependencies"
+  COMPOSER_URL="http://getcomposer.org/composer.phar"
+  curl --silent --max-time 60 --location "$COMPOSER_URL" > www/composer.phar
+  cd www
+  LD_LIBRARY_PATH=$BUILD_DIR/php/ext $BUILD_DIR/php/bin/php -c $LP_DIR/conf/php.ini composer.phar install --prefer-source
+  rm -rf vendor/**/.git
+  cd $BUILD_DIR
+  rm www/composer.phar
+  export GIT_DIR=$GIT_DIR_ORIG
+fi
+
+cat >>boot.sh <<EOF
+for var in \`env|cut -f1 -d=\`; do
+  echo "PassEnv \$var" >> /app/apache/conf/httpd.conf;
 done
+touch /app/apache/logs/error_log
+touch /app/apache/logs/access_log
+tail -F /app/apache/logs/error_log &
+tail -F /app/apache/logs/access_log &
+export LD_LIBRARY_PATH=/app/php/ext
+export PHP_INI_SCAN_DIR=/app/www
+echo "Launching apache"
+exec /app/apache/bin/httpd -DNO_DETACH
+EOF
 
-arrow "Starting adding ODBC Driver ${MS_ODBC_VERSION} for SQL Server"
-mkdir -p "${BUILD_DIR}/.apt/usr/lib/odbc/conf/" | indent
-mkdir -p "${BUILD_DIR}/.apt/usr/share/resources/en_US/" | indent
-cp -a "${BUILD_DIR}/.apt/opt/microsoft/msodbcsql${MS_ODBC_VERSION}/lib64/." "${BUILD_DIR}/.apt/usr/lib/" | indent
-arrow "copied libmsodbcsql-${MS_ODBC_VERSION}-*"
-cp -a "${BUILD_DIR}/.apt/opt/microsoft/msodbcsql${MS_ODBC_VERSION}/share/resources/en_US/." "${BUILD_DIR}/.apt/usr/share/resources/en_US/" | indent
-arrow "copied msodbcsqlr${MS_ODBC_VERSION}.rll"
+chmod +x boot.sh
 
-mkdir -p "${BUILD_DIR}/.profile.d" | indent
-cp .profile.d/configure-odbc.sh "${BUILD_DIR}/.profile.d" | indent
-arrow "copied profile.d !!!!!!!"
-arrow "Finished adding ODBC Driver ${MS_ODBC_VERSION} for SQL Server"
-
-arrow "Download .so"
-wget  https://github.com/robuust/heroku-php/raw/pdo_sqlsrv/packages/ext-pdo_sqlsrv-5.10.1_php-8.1.tar.gz
-ls -la .
-mkdir -p ./.heroku/php/
-mkdir -p ./.heroku/php/etc/php/conf.d
-tar -xvf ext-pdo_sqlsrv-5.10.1_php-8.1.tar.gz -C ./.heroku/php/
-echo extension=pdo_sqlsrv.so >> ./.heroku/php/etc/php/conf.d/100-ext-sqlsrv.ini
+# clean the cache
+rm -rf $CACHE_DIR/*
